name: build-and-deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
  id-token: write
  pages:    write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: '3.12'}
    - run: pipx install uv
    - run: make build
    - uses: actions/upload-pages-artifact@v3
      with: {path: site}
    - uses: actions/deploy-pages@v4
